### ISSUE TITLE
Deploy sscheck backend to Staging

### ISSUE THREAD

**Issue by victorskl** [umccr/samplesheet-check-backend#55]
**Context:**

OrcaBus basespace raw data copy upload service `bs-runs-upload-manager` needs to translate `SampleSheet.v2.csv` as part of the process.

The `bs-runs-upload-manager` rely up sscheck API backend for this part.

So far sscheck stack deployed to DEV and PROD. We would also need it to deploy into Staging account.

**Related:**

See downstream story at orcabus:

- https://github.com/umccr/orcabus/issues/265
- https://github.com/umccr/orcabus/pull/338

**Actions:**

- Deploy to Staging

**Comment by victorskl** [comment]
@williamputraintan Welcome back, Will. 

Could you help drive this story, pls? This task in the critical path for OrcaBus release Phase 1.

**Comment by victorskl** [comment]
Will started working with branch: [feat/55-stg-deployment](https://github.com/umccr/samplesheet-check-backend/tree/feat/55-stg-deployment)

**Comment by williamputraintan** [comment]
Deployed to `STG` account
