### ISSUE TITLE
Check Lambda performance

### ISSUE THREAD

**Issue by reisingerf** [umccr/samplesheet-check-backend#6]
Profile validation lambda. 
Invocations seem to take ~17sec average, which seems way too long.

(Perhaps investigate use of xRay...)

**Comment by williamputraintan** [comment]
Improvement had been made on this PR [c633a87](https://github.com/umccr/samplesheet-check-backend/commit/c633a873d42fc2895fce5de4da749b45d8a9704b), but could still be optimize more in the future.

Things to note:
1. Improve lambda coldstart. 
    - One way is to increase memory allocation to the lambda as a result, lambda might get a better instances to run the job even if not all memory defined will all be used.
2. Improve [check_sample_sheet_for_index_clashes()](https://github.com/umccr/samplesheet-check-backend/blob/a61c57f25cec20c231033178f880c62d6e79c901/lambdas/layers/umccr_utils/samplesheet.py#L562-L636):
    - On large samplesheet (with ~300 samples), this could take up to 13 seconds alone. Most time taken is [generating hamming distance](https://github.com/umccr/samplesheet-check-backend/blob/a61c57f25cec20c231033178f880c62d6e79c901/lambdas/layers/umccr_utils/samplesheet.py#L782) between samples. Might find alternative if possible.

**Comment by williamputraintan** [comment]
Improved on lambda performance by increasing memory as mention in point number 1 above.

According to the lambda memory [config docs](https://docs.aws.amazon.com/lambda/latest/dg/configuration-function-common.html#configuration-memory-console) "_At 1,769 MB, a function has the equivalent of one vCPU_".
Using [lambda-power-tuning](https://github.com/alexcasalboni/aws-lambda-power-tuning) to check the best time corresponding to the memory used. Shows that around 1769MB has reached the maximum average fastest time for the lambda. Reducing time from 22s to 1.5s

Chart Result: 
https://lambda-power-tuning.show/#gAAAAQACGATcBekG0AfECcAL;+wSxRh9JN0Z0dqVFM8ckRYx160TaQMdEGAPORKvSxUQOnMtE;05RHOHmnTjjkjTo4Xis+OAh3Qji7KEI40vFiONApiDisl6g4

Closing this issue for now.
